version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  db:
    image: mysql:8  # ✅ 替换为官方 MySQL 镜像
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: eye_db         # ✅ 添加此行，自动创建数据库
    ports:
      - "3307:3306"
    volumes:
      - ./.data:/var/lib/mysql


